version: '3'
services:
  # lightstream:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile  # Adjust if your Dockerfile has a different name
  #     args:
  #       FDB_VERSION: ${FDB_VERSION}
  #   network_mode: host
  #   environment:
  #     FDB_COORDINATOR: ${FDB_COORDINATOR}
  #     FDB_API_VERSION: ${FDB_API_VERSION}
  #   ports:
  #     - 50051:50051/tcp
  #   depends_on:
  #     - fdb-coordinator
  #     - fdb-server-1
  #     - fdb-server-2
  # # Specify three fdbserver processes.
  fdb-coordinator:
    image: foundationdb/foundationdb:${FDB_VERSION}
    ports:
      - 4500:4500/tcp
    environment:
      FDB_COORDINATOR: ${FDB_COORDINATOR}
      FDB_NETWORKING_MODE: ${FDB_NETWORKING_MODE}
      FDB_COORDINATOR_PORT: ${FDB_COORDINATOR_PORT}

  fdb-server-1:
    depends_on:
      - fdb-coordinator
    image: foundationdb/foundationdb:${FDB_VERSION}
    environment:
      FDB_COORDINATOR: ${FDB_COORDINATOR}
      FDB_NETWORKING_MODE: ${FDB_NETWORKING_MODE}
      FDB_COORDINATOR_PORT: ${FDB_COORDINATOR_PORT}

  fdb-server-2:
    depends_on:
      - fdb-coordinator
    image: foundationdb/foundationdb:${FDB_VERSION}
    environment:
      FDB_COORDINATOR: ${FDB_COORDINATOR}
      FDB_NETWORKING_MODE: ${FDB_NETWORKING_MODE}
      FDB_COORDINATOR_PORT: ${FDB_COORDINATOR_PORT}
